# Матричные операции. Часть 1

#### __1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

Варианты матриц а) и б) не перемножаются друг на друга, так как кол-во строк и столбцов у них попарно не совпадает. Если бы в а) были матрицы 4х2 и 2х4 - можно было бы перемножить. Вариант б) должен был быть 2х5 и 5х2, либо 3х5 и 5х3.

Вариант в). Размерность будет 8х8, так как каждая строка умножается на каждый столбец

Вариант г). Матрица останется квадратной, т.е. 4х4

#### _после просмотра разбора_:

чтобы перемножить матрицы, надо чтобы кол-во столбцов у первой совпадало с кол-вом строк у второй, строки первой могут не совпадать с кол-вом столбцов второй

кроме того, я забыл про умножение В на А

поэтому:

а) Все еще нельзя перемножать

б) AB можно умножить (2х3), BA нельзя

в) AB будет 8х8, ВА будет 3х3

г) можно, останется квадратной

#### __2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

<img src="./img_l2/1-2.jpg" alt="Drawing" style="width: 600px;"/>

In [1]:
import numpy as np

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

In [3]:
print(A + B)

[[ 5 -3]
 [ 3  5]]


In [4]:
print(A @ B)

[[  4 -11]
 [ 12  -3]]


In [5]:
print(B @ A)

[[ 1 -8]
 [15  0]]


#### __3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

<img src="./img_l2/1-3.jpg" alt="Drawing" style="width: 600px;"/>

In [6]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

In [7]:
print(3 * A - 2 * B + 4 * C)

[[ 11  -5]
 [  9 -12]]


#### __4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

<img src="./img_l2/1-4.jpg" alt="Drawing" style="width: 600px;"/>

In [10]:
A = np.array([[4, 1], [5, -2], [2, 3]])
AT = A.T

print(f'{A}\n\n{AT}')

[[ 4  1]
 [ 5 -2]
 [ 2  3]]

[[ 4  5  2]
 [ 1 -2  3]]


In [12]:
print(A @ AT)

[[17 18 11]
 [18 29  4]
 [11  4 13]]


In [13]:
print(AT @ A)

[[45  0]
 [ 0 14]]


#### __5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [80]:
def matr_transp(A):
    AT = [[] for el in range(len(A[0]))]
    for i1 in range(len(A[0])):
        for i2 in range(len(A)):
            AT[i1].append(A[i2][i1])
        
    return AT

def matr_mult(A, B):
    
#     if len(A) == len(B[0]) and len(A[0]) == len(B):
#     посмотрел разбор, главное чтобы совпадали кол-во столбцов первой матрицы с кол-вом строк второй, поэтому:
      if len(A[0]) == len(B):
        
        C = [[0 for el in range(len(A))] for el in range(len(A))]
        BT = matr_transp(B)
#         print(C)
#         print(BT)
        
        for i1 in range(len(A)):
#             print(f'i1: {i1}')
            for i2 in range(len(A)):
#                 print(f'i2: {i2}')
                
                for i3 in range(len(B)):
#                     print(f'i3: {i3}')
                    C[i1][i2] += A[i1][i3] * BT[i2][i3]
        
        return C
    
    else:
        print(f'You have to put properly shaped matrixes in here :/')

Часа полтора кумекал над этой функцией, нравится как в итоге получилось) Наверное, можно было обойтись без транспонирования второй матрицы, но я решил, что гулять, так гулять))) 

И сделал еще микро функцию для транспонирования, чтобы потом красиво скалярно умножать строку на строку, а не строку на столбец)

In [79]:
A = np.array([[1, 7], [3, -6], [5, -9]])
B = np.array([[0, 5, 4], [2, -1, 7]])

print(f'{A}\n\n{B}')

[[ 1  7]
 [ 3 -6]
 [ 5 -9]]

[[ 0  5  4]
 [ 2 -1  7]]


In [81]:
print(matr_mult(A, B))

[[14, -2, 53], [-12, 21, -30], [-18, 34, -43]]


In [77]:
print(A @ B)

[[ 14  -2  53]
 [-12  21 -30]
 [-18  34 -43]]


ниже мои ✨скетчи✨, пытался уложить в голове, как именно матрицы можно перенести в питон, типо структура списков в списках. Тройной цикл надо было выдумать, транспонировать матрицу для удобства и тд.

<img src="./img_l2/1-5.jpg" alt="Drawing" style="width: 600px;"/>

# Матричные операции. Часть 2

#### __1.__ Вычислить определитель:

   a)

$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$

   б)
    
$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$
    
   в)

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$

<img src="./img_l2/2-1.jpg" alt="Drawing" style="width: 600px;"/>

In [93]:
A = np.array([[np.sin(1), np.cos(1) * -1], [np.cos(1), np.sin(1)]])
B = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [99]:
print(f"Определитель матрицы А:\n{np.linalg.det(A)}")
print(f"Определитель матрицы B:\n{np.linalg.det(B)}")

print(f'Определитель матрицы C:\n{np.linalg.det(C)}')
print(f'Определитель матрицы C (посчитан вручную...):\n{1*(5*9 - 8*6) - 2*(4*9 - 7*6) + 3*(4*8 - 7*5)}')

Определитель матрицы А:
1.0
Определитель матрицы B:
180.0
Определитель матрицы C:
6.66133814775094e-16
Определитель матрицы C (посчитан вручную...):
0


#### __2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а) 16, просто методом подбора проверил на двух квадратных матрицах 2х2. Определитель возводится в степень, в которую возводят саму матрицу

если определитель был 16 и матрицу возвести в квадрат - детерминатор станет 256

б) определитель будет 4, по первому свойству из методички, у транспонированой и обычной матрицы определители одинаковые.

в) 16, тоже самое, просто проверил, посчитав руками... Определитель считает не совсем очевидным образом, у меня получилось:

det(kA) = det(A) * k^2, 
где k - множитель матрицы

в нашем случае получается k=2, 4 * 2^2 = 16,

если k=3, 4 * 3^2 = 36,

если k=4, 4 * 4^2 = 64,

если k=5, 4 * 5^2 = 100

_просто вручную считал варианты определителей разных_ 👇

<img src="./img_l2/2-2.jpg" alt="Drawing" style="width: 600px;"/>

#### _после просмотра разбора удивлен, что правильно нашел как быть с определителем при умножении матрицы))) Хоть и методом тыка, но правильно))_

#### __3.__  Доказать, что матрица вырожденная.

$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$

In [101]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])

print(np.linalg.det(A))

0.0


Так как определитель матрицы 0 - матрица вырожденная 

#### __4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

а) ранг матрицы 2, так как третья строчка - это вектор, полученный сложением первых двух строк


б) матрица содержит не нулевые значения, значит ранг ее не меньше 1, но и не больше 4 из-за кол-ва строк/столбцов 

третья строка может быть выражена через сложение первых двух, вычеркиваем ее. Теперь ранг матрицы не больше 3

матрица: $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

ищу через миноры не нулевые определители, сначала второго порядка. Определитель минора: $\begin{vmatrix}
2 & 1\\ 
2 & 2
\end{vmatrix}$ = 1, значит ранг матрицы минимум 2 и максимум 3

теперь смотрю миноры третьего порядка. Определитель минора: $\begin{vmatrix}
0 & 2 & 1\\
0 & 2 & 2\\
3 & 5 & 6
\end{vmatrix}$ = 6, **значит ранг матрицы б) = 3**

**прошу прощения за дикие задержки по дедлайнам...**